# Generated by Django 4.1.3 on 2022-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_provider', models.CharField(max_length=30)),
                ('service_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.TextField(default='Abuja')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
