# Generated by Django 4.1.3 on 2022-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proudcts',
            name='summary',
            field=models.TextField(default='This is an example of a default text'),
        ),
    ]
