# Generated by Django 4.1.3 on 2022-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_proudcts_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudcts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='proudcts',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
