# Generated by Django 4.1.3 on 2022-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_proudcts_featured_alter_proudcts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudcts',
            name='summary',
            field=models.TextField(default='This is an example of a default text', null=True),
        ),
    ]
