# Generated by Django 4.1.3 on 2022-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_proudcts_description_alter_proudcts_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudcts',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
